myexe: myStrFunc.o myMathFunc.o main.o
	gcc -o myexe myStrFunc.o myMathFunc.o main.o
myStrFunc.o: myStrFunc.c
	gcc -c myStrFunc.c
myMathFunc.o: myMathFunc.c
	gcc -c myMathFunc.c
main.o: main.c
	gcc -c main.c

